const express = require('express');
const AccountantLogs = require('../models/AccountantLogs');
const router = express.Router();

//Get All Logs Generated by the system
router.get('/getAll', (req, res) => {
    AccountantLogs.find({})
        .exec(function(err, allLogs) {
            if (err) return handleError(err);
            res.json({
                success: true,
                msg: 'All Logs Fetched',
                logs: allLogs,
            });
        });
});


// @desc Logs entry to system
//  @route POST / saveLog
router.post('/saveLog', (req, res) => {
    let uniLog = new AccountantLogs({
        paymentDate: req.body.paymentDate,
        rollNo: req.body.rollNo,
        studentFullName: req.body.studentFullName,
        studentFatherName: req.body.studentFatherName,
        batch: req.body.batch,
        paymentAmount: req.body.paymentAmount,
        modeOfPayment: req.body.modeOfPayment
    });

    AccountantLogs.createAccountantLogs(uniLog, (err, logs) => {
        if (err) {
            res.json({ success: false, msg: 'Failed To log the transaction' });
        } else {
            res.json({
                success: true,
                msg: 'Log created successfully',
                log: uniLog,
            });
        }
    });
});

module.exports = router;